"""
Strategy Lab - Generates and evaluates strategic hypotheses
Part of Layer 1: Strategic Intelligence Core
"""

from typing import List, Dict, Any, Optional
from dataclasses import dataclass
from datetime import datetime


@dataclass
class StrategicHypothesis:
    """A strategic hypothesis generated by the Strategy Lab"""
    id: str
    title: str
    description: str
    domain: str
    expected_outcome: str
    risk_level: str  # low, medium, high
    confidence: float  # 0.0 - 1.0
    prerequisites: List[str]
    created_at: datetime
    status: str = "draft"  # draft, simulated, approved, rejected


class StrategyLab:
    """
    Strategy Lab is responsible for strategy generation and evaluation.
    
    Responsibilities:
    - Identify opportunities
    - Generate strategic hypotheses
    - Evaluate and rank strategies
    """
    
    def __init__(self):
        self.hypotheses: List[StrategicHypothesis] = []
        self.opportunity_areas: List[Dict[str, Any]] = []
    
    def generate_hypothesis(self, opportunity: Dict[str, Any]) -> StrategicHypothesis:
        """Generate a strategic hypothesis from an identified opportunity"""
        hypothesis = StrategicHypothesis(
            id=f"hypo_{len(self.hypotheses) + 1}_{datetime.now().timestamp()}",
            title=opportunity.get("title", "Untitled Strategy"),
            description=opportunity.get("description", ""),
            domain=opportunity.get("domain", "general"),
            expected_outcome=opportunity.get("expected_outcome", ""),
            risk_level=opportunity.get("risk_level", "medium"),
            confidence=opportunity.get("confidence", 0.5),
            prerequisites=opportunity.get("prerequisites", []),
            created_at=datetime.now()
        )
        self.hypotheses.append(hypothesis)
        return hypothesis
    
    def identify_opportunities(self, signals: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Identify strategic opportunities from signals"""
        opportunities = []
        
        for signal in signals:
            # Simple pattern matching - expand with ML in production
            if signal.get("type") == "opportunity_signal":
                opportunities.append({
                    "title": signal.get("title", "New Opportunity"),
                    "description": signal.get("description", ""),
                    "domain": signal.get("domain", "general"),
                    "expected_outcome": signal.get("expected_outcome", ""),
                    "risk_level": signal.get("risk_level", "medium"),
                    "confidence": signal.get("confidence", 0.5),
                    "source_signal_id": signal.get("id")
                })
        
        self.opportunity_areas.extend(opportunities)
        return opportunities
    
    def evaluate_hypothesis(self, hypothesis_id: str, simulation_results: Dict[str, Any]) -> Dict[str, Any]:
        """Evaluate a hypothesis based on simulation results"""
        hypothesis = next((h for h in self.hypotheses if h.id == hypothesis_id), None)
        
        if not hypothesis:
            return {"error": "Hypothesis not found"}
        
        # Evaluate based on simulation outcomes
        success_rate = simulation_results.get("success_rate", 0.0)
        risk_score = simulation_results.get("risk_score", 0.5)
        
        evaluation = {
            "hypothesis_id": hypothesis_id,
            "success_rate": success_rate,
            "risk_score": risk_score,
            "recommendation": "approve" if success_rate > 0.7 and risk_score < 0.4 else "revise",
            "evaluated_at": datetime.now().isoformat()
        }
        
        if evaluation["recommendation"] == "approve":
            hypothesis.status = "simulated"
        
        return evaluation
    
    def rank_strategies(self, domain: Optional[str] = None) -> List[StrategicHypothesis]:
        """Rank strategies by confidence and risk level"""
        filtered = self.hypotheses
        if domain:
            filtered = [h for h in self.hypotheses if h.domain == domain]
        
        # Sort by confidence (descending) and risk level (ascending)
        risk_order = {"low": 0, "medium": 1, "high": 2}
        ranked = sorted(
            filtered,
            key=lambda h: (h.confidence, -risk_order.get(h.risk_level, 1)),
            reverse=True
        )
        return ranked
    
    def get_pending_strategies(self) -> List[StrategicHypothesis]:
        """Get strategies pending evaluation"""
        return [h for h in self.hypotheses if h.status in ["draft", "simulated"]]
